# Generated by Django 5.1.4 on 2025-02-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="whatsapp.contact",
            ),
        ),
    ]
