# Generated by Django 5.1.4 on 2025-02-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_alter_whatsappmessage_sender"),
    ]

    operations = []
