# Generated by Django 5.1.4 on 2025-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0004_auto_20250207_1309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="sender",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
