# Generated by Django 5.1.4 on 2025-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_organization_alter_whatsappmessage_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="sender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
