# Generated by Django 5.1.4 on 2025-02-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0007_alter_whatsappmessage_sender"),
    ]

    operations = []
