# Generated by Django 5.1.4 on 2025-02-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("audio_file", models.FileField(upload_to="")),
                ("feature_text", models.TextField(blank=True, null=True)),
                ("file_size", models.PositiveIntegerField(null=True)),
                ("duration", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("talk_time", models.TimeField()),
                ("case_id", models.CharField(max_length=20)),
                ("narrative", models.TextField()),
                ("plan", models.TextField()),
                ("main_category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("gbv", models.BooleanField()),
                (
                    "unique_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.audiofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_text", models.TextField()),
                ("wer", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in-progress",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transcription.audiofile",
                    ),
                ),
                (
                    "model_version_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transcription.modelversion",
                    ),
                ),
            ],
        ),
    ]
