# Generated by Django 5.1.4 on 2025-02-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="feature_text",
        ),
        migrations.AlterField(
            model_name="modeltranscription",
            name="audio_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="transcription.audiofile",
            ),
        ),
        migrations.AlterField(
            model_name="modeltranscription",
            name="wer",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AudioFileChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_file", models.FileField(upload_to="audio_chunks/")),
                ("order", models.PositiveIntegerField()),
                ("duration", models.FloatField(null=True)),
                ("true_transcription", models.TextField(blank=True, null=True)),
                ("is_rejected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="transcription.audiofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_audio", "order")},
            },
        ),
        migrations.AddField(
            model_name="modeltranscription",
            name="audio_chunk_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="transcription.audiofilechunk",
            ),
        ),
    ]
