# Generated by Django 5.1.4 on 2025-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complaint_audio",
            field=models.FileField(
                blank=True, null=True, upload_to="complaints/audio/"
            ),
        ),
    ]
